import os
import glob

headers = []
for root, dirnames, filenames in os.walk("."):
	directory_headers = glob.glob(root + "/*.h")
	for h in directory_headers:
		headers.append(h[2:])

f = open("pcf.h", "w")
f.writelines([
	"// File automatically generated by generate_pcf_h.h\n",
	"\n",
	"#ifndef PCF_PCF_H_\n"
	"#define PCF_PCF_H_\n"
	"\n"
])

for h in headers:
	f.write("#include \"" + h + "\"\n")

f.writelines([
	"\n"
	"#endif\n"
])